/**
 * OpenCV Descriptor Service
 *
 * Manages ORB feature descriptors for artifact/exhibition images.
 * Descriptors are generated server-side and served to the frontend
 * for client-side OpenCV.js matching.
 *
 * Descriptor lifecycle:
 * 1. Generated on artifact/exhibition image upload
 * 2. Stored as JSON files in uploads/descriptors/
 * 3. Served to frontend via GET /api/ar/descriptors
 * 4. Frontend OpenCV.js matches camera frames against descriptors
 * 5. Rebuilt via POST /api/admin/descriptors/rebuild
 */
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import crypto from 'crypto';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const DESCRIPTOR_DIR = path.join(__dirname, '..', '..', 'uploads', 'descriptors');

// Ensure descriptor directory exists
const ensureDir = async () => {
  await fs.mkdir(DESCRIPTOR_DIR, { recursive: true });
};

/**
 * Generate a hash for an image file to detect changes.
 */
const hashImage = async (imagePath) => {
  const buffer = await fs.readFile(imagePath);
  return crypto.createHash('sha256').update(buffer).digest('hex');
};

/**
 * Get descriptor file path for an entity.
 */
const getDescriptorPath = (entityType, entityId) => {
  return path.join(DESCRIPTOR_DIR, `${entityType}_${entityId}.json`);
};

/**
 * Save descriptor data for an entity.
 * Descriptors are computed client-side with OpenCV.js and uploaded,
 * OR generated by the YOLO service's OpenCV endpoint.
 */
const saveDescriptor = async (entityType, entityId, descriptorData) => {
  await ensureDir();
  const filePath = getDescriptorPath(entityType, entityId);
  const data = {
    entityType,
    entityId,
    version: 1,
    generatedAt: new Date().toISOString(),
    ...descriptorData,
  };
  await fs.writeFile(filePath, JSON.stringify(data));
  return data;
};

/**
 * Load descriptor data for an entity.
 */
const loadDescriptor = async (entityType, entityId) => {
  const filePath = getDescriptorPath(entityType, entityId);
  try {
    const raw = await fs.readFile(filePath, 'utf-8');
    return JSON.parse(raw);
  } catch {
    return null;
  }
};

/**
 * Load all descriptors for a given entity type.
 */
const loadAllDescriptors = async (entityType = null) => {
  await ensureDir();
  const files = await fs.readdir(DESCRIPTOR_DIR);
  const descriptors = [];

  for (const file of files) {
    if (!file.endsWith('.json')) continue;
    if (entityType && !file.startsWith(`${entityType}_`)) continue;

    try {
      const raw = await fs.readFile(path.join(DESCRIPTOR_DIR, file), 'utf-8');
      descriptors.push(JSON.parse(raw));
    } catch {
      // Skip corrupted files
    }
  }

  return descriptors;
};

/**
 * Delete descriptor for an entity.
 */
const deleteDescriptor = async (entityType, entityId) => {
  const filePath = getDescriptorPath(entityType, entityId);
  await fs.unlink(filePath).catch(() => {});
};

/**
 * Validate all descriptors — remove orphaned ones.
 */
const validateDescriptors = async (getValidIds) => {
  await ensureDir();
  const files = await fs.readdir(DESCRIPTOR_DIR);
  const validIds = await getValidIds();
  const removed = [];

  for (const file of files) {
    if (!file.endsWith('.json')) continue;
    const [type, id] = file.replace('.json', '').split('_');
    const key = `${type}_${id}`;
    if (!validIds.has(key)) {
      await fs.unlink(path.join(DESCRIPTOR_DIR, file)).catch(() => {});
      removed.push(key);
    }
  }

  return removed;
};

export {
  saveDescriptor,
  loadDescriptor,
  loadAllDescriptors,
  deleteDescriptor,
  validateDescriptors,
  hashImage,
  ensureDir,
  DESCRIPTOR_DIR,
};
